---
 - debug: var=postgres_role
 - name: install epel
   yum:
     name: epel-release
     state: present
 - name: install common packages
   yum:
     name: python-pip
     state: present
 - name: install pip packages
   pip:
     name: psycopg2
 - name: set variables for postgres 10
   set_fact:
     postgres_rpm: pgdg-centos10-10-2.noarch.rpm
     postgres_packet: postgresql10-server.x86_64
     postgres_init_command: /usr/pgsql-10/bin/postgresql-10-setup initdb
     postgres_systemd_service: postgresql-10
     postgres_data_folder: /var/lib/pgsql/10/data/
   when:
     - version == 10.2
 - name: set variables for postgres 9
   set_fact:
     postgres_rpm: pgdg-centos96-9.6-3.noarch.rpm
     postgres_packet: postgresql96-server.x86_64
     postgres_init_command: /usr/pgsql-9.6/bin/postgresql96-setup initdb
     postgres_systemd_service: postgresql-9.6
     postgres_data_folder: /var/lib/pgsql/9.6/data/
   when:
     - version == 9.6
 - debug: var=postgres_rpm
 - name: copy rpm on host
   copy:
     src: "{{ postgres_rpm }}"
     dest: /tmp/
 - name: install postgres repo
   yum:
     name: /tmp/{{ postgres_rpm }}
     state: present
 - name: install postgres server
   yum:
     name: "{{ postgres_packet }}"
     state: present
 - name: init db
   shell: "{{ postgres_init_command }}"
 - name: start postgres
   systemd:
     name: "{{ postgres_systemd_service }}"
     state: started
 - name: change postgres password
   become: true
   become_user: postgres
   postgresql_user:
     db: postgres
     name: postgres
     password: "{{ slave_password }}"
 - name: download pg_hba 9.6
   template:
     src: pg_hba.conf.j2
     dest: /var/lib/pgsql/9.6/data/pg_hba.conf
  # template не поддерживает переменные   
  #  dest: "{{ postgres_data_folder }}"/pg_hba.conf
   when:
      - version == 9.6
 - name: download postgresql.conf 9.6
   template:
     src: postgresql.conf.j2
     dest: /var/lib/pgsql/9.6/data/postgresql.conf
     # dest: "{{ postgres_data_folder }}"/postgresql.conf
   when:
     - version == 9.6
 - name: download pg_hba 10
   template:
     src: pg_hba.conf.j2
     dest: /var/lib/pgsql/10/data/pg_hba.conf
  # template не поддерживает переменные   
  #  dest: "{{ postgres_data_folder }}"/pg_hba.conf
   when:
      - version == 10.2
 - name: download postgresql.conf 10
   template:
     src: postgresql.conf.j2
     dest: /var/lib/pgsql/10/data/postgresql.conf
     # dest: "{{ postgres_data_folder }}"/postgresql.conf
   when:
     - version == 10.2

 - name: restart postgresql
   systemd:
     name: "{{ postgres_systemd_service }}"
     state: restarted

 - name: create replica
   become: true
   become_user: postgres
   postgresql_user:
     db: postgres
     name: replica
     password: "{{ slave_password }}" 
     role_attr_flags: LOGIN,REPLICATION
     login_password: "{{ slave_password }}"
   when:
     - postgres_role == 'master'
 
 - name: stop postgres on slave
   systemd:
     name: "{{ postgres_systemd_service }}"
     state: stopped
   when: 
     - postgres_role == 'slave'

 - name: clean data
   file:
     path: "{{ postgres_data_folder }}"
     state: absent
   when:
     - postgres_role == 'slave'

 - name: copy from master
   become: true
   become_user: postgres
   shell: export PGPASSWORD="{{ slave_password }}" && pg_basebackup -R -P -X stream -c fast -h {{ master_ip }} -U replica -D {{ postgres_data_folder }}
   when:
     - postgres_role == 'slave'
 
 - name: start slave
   systemd:
     name: "{{ postgres_systemd_service }}"
     state: started
   when: 
     - postgres_role == 'slave'
